// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://mahjong-api.onrender.com' | (string & {});
};

/**
 * DragonValue
 */
export type DragonValue = 'red' | 'green' | 'white';

/**
 * GameCreateSchema
 */
export type GameCreateSchema = {
    [key: string]: unknown;
};

/**
 * GameDetailSchema
 */
export type GameDetailSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Hands
     */
    hands: Array<HandOutSchema>;
};

/**
 * GameOutSchema
 */
export type GameOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HandCreateSchema
 */
export type HandCreateSchema = {
    /**
     * Melds
     */
    melds: Array<MeldSchemaInput>;
    pair: TileSchema;
    /**
     * Game Id
     */
    game_id: number;
};

/**
 * HandOutSchema
 */
export type HandOutSchema = {
    /**
     * Melds
     */
    melds: Array<MeldSchemaOutput>;
    pair: TileSchema;
    /**
     * Game Id
     */
    game_id: number;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * MeldSchema
 */
export type MeldSchemaInput = {
    type: MeldType;
    tile: TileSchema;
};

/**
 * MeldSchema
 */
export type MeldSchemaOutput = {
    type: MeldType;
    tile: TileSchema;
};

/**
 * MeldType
 */
export type MeldType = 'chow' | 'pong' | 'kong';

/**
 * NumberValue
 */
export type NumberValue = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';

/**
 * Suit
 */
export type Suit = 'circle' | 'bamboo' | 'character' | 'wind' | 'dragon';

/**
 * TileSchema
 */
export type TileSchema = {
    suit: Suit;
    /**
     * Value
     */
    value: NumberValue | WindValue | DragonValue;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WindValue
 */
export type WindValue = 'east' | 'south' | 'west' | 'north';

export type ScoreHandData = {
    body: HandCreateSchema;
    path?: never;
    query?: never;
    url: '/hands/score';
};

export type ScoreHandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreHandError = ScoreHandErrors[keyof ScoreHandErrors];

export type ScoreHandResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadGamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/games/';
};

export type ReadGamesResponses = {
    /**
     * Response Readgames
     * Successful Response
     */
    200: Array<GameOutSchema>;
};

export type ReadGamesResponse = ReadGamesResponses[keyof ReadGamesResponses];

export type CreateGameData = {
    body: GameCreateSchema;
    path?: never;
    query?: never;
    url: '/games/';
};

export type CreateGameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGameError = CreateGameErrors[keyof CreateGameErrors];

export type CreateGameResponses = {
    /**
     * Successful Response
     */
    200: GameOutSchema;
};

export type CreateGameResponse = CreateGameResponses[keyof CreateGameResponses];

export type ReadGameByIdData = {
    body?: never;
    path: {
        /**
         * Game Id
         */
        game_id: number;
    };
    query?: never;
    url: '/games/{game_id}';
};

export type ReadGameByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGameByIdError = ReadGameByIdErrors[keyof ReadGameByIdErrors];

export type ReadGameByIdResponses = {
    /**
     * Successful Response
     */
    200: GameDetailSchema;
};

export type ReadGameByIdResponse = ReadGameByIdResponses[keyof ReadGameByIdResponses];

export type ReadRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApiEndpointSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type GetApiEndpointSummaryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
